### ISSUE TITLE
Feedback about Zoom Breakout rooms

### ISSUE THREAD

**Issue by drshrirang** [carpentries/community-facilitators-program#21]
1.	Date: May 28th 2020
Name: Lex Nederbragt
**Positive :** 
•	Breakout rooms in Zoom are great and have multiple use cases during online training. 
•	They can be used to have learners work in smaller groups on assignments. 
•	They can also be used to put a learner together with a helper to quickly solve an immediate technical issue
**Concern:**
•	I just realised today (doing a workshop) that these uses can become in conflict: I had set up all breakout rooms with learners because we were going to do the first exercise, and then a learner got stuck and needed help. I accidentally opened all rooms and learners started to move into them. I could not set up and open one single room for the stuck learner and a helper, unless I reset all rooms again. I'd love to hear your thoughts on how to work around this problem...
April 23rd, 2020
•	Oh, multiple screen share in Zoom, should try that out (also in breakout rooms)!

2.	Date: May 18th 2020
Name: Sarah M Brown
**Positive:** 
•	The two instructors moved through the breakout rooms to check on groups.

May 25th, 2020
•	Breakout room  it really helped class feel real. She even shared that if described she would have thought it was cheesy, but having experienced it, she greatly appreciated it

3.	Date: May 14th 2020
Name: Scott Henderson
**Concern:** 
•	One particular issue was going into breakout rooms, the invitation stayed hidden behind my shared screen and I had to right-click zoom --> ‘show all windows’  --> join breakout room

4.	 Date: May 18th 2020
Name: Clark Gaylord
**Concern:** 
•	But I think if you wanted an ad hoc remote desktop session in a one-on-one breakout room that would probably work. The usual application of breakout rooms is to segment the entire class into one of several available rooms (and it will auto randomly assign if you want). 
•	But I think manually assigning a single student to a room might work. Problem of course is that then you are leaving the main room. Not ideal. Agreed a helper or TA would be closer to ideal.

5.	Date: April 23rd,  2020
Name: Brian Ballsun-Stanton
**Concern:** 
•	The most common complaint from zoom and our learners were those with single screens were hopelessly lost after breakout rooms, because I had them have chat and participant windows open as well as main.

6.	Date: May 28th,  2020
Name: Naoe Tatara
**Positive:** 
•	What helped me quickly assign learners into  breakout rooms was renaming them to (ROOM NUMBER(,H (if helper)))_NAME so that they are in the alphabetically sorted and easy for me to assign to each room. 
•	If the number of participants is relatively small, it might be helpful not prepare all the breakout rooms beforehand, but rather right before the session starts?
**Concern:**
•	yes it is painful to reset everything to open a single breakout room only for allocating the one with a problem plus a helper, and close it when they are done, and assign all the participants again into breakout rooms and open them when group session starts.

7.	Date: Oct 1st ,  2020
Name: Jamie Jamison
**Concern:**
•	Shouldn't I see the button for breakout rooms at the bottom of the zoom window?

8.	Date: May 28th ,  2020
Name: Angelique van Rensburg
**Concern:**
•	Breakout rooms can definitely be very helpful but tricky at the same time. In my experience (with low bandwidth connections) when moving individuals to Breakout rooms some learners lose connection to the call.

**Final Call:**
Positive: 3
Concern: 7

Shrirang Recommendation

- Dedicated carpentry page on GitHub elaborating the usage of breakout rooms in Zoom for specific version and platform .

- Also an elaborate FAQ’s for a comprehensive reference for any potential technical disruptions.

- Feedback about features like Zoom Breakout rooms could be taken during a live session like a quiz question to determine the difficulty or ease of use of the same.

**Comment by maneesha** [comment]
I am going to be re-organizing our handbook content so we are not maintaining our own Zoom documentation (which gets outdated and can be inaccurate), but rather link directly to Zoom's documentation.  Keep in mind the views will depend on the user's own set up and operating system.  Any Zoom functionality is also dependent on having the most up to date version of Zoom installed (this changes often!).

**Comment by kariljordan** [comment]
Thanks @maneesha, would you say your updates of the handbook resolve this issue?
