### ISSUE TITLE
Spam and phishing messages in topicbox

### ISSUE THREAD

**Issue by annajiat** [carpentries/community-facilitators-program#38]
A number of spam/junk messages are there in the topic box posted over the months. Community members marking those as a spam in their email clients might lead to other legitimate emails be judged as spam in future.

Example of mailing list:
https://carpentries.topicbox.com/groups/local-middle-east

Potential Example of spam:
March 2, https://carpentries.topicbox.com/groups/local-middle-east/T7c887775dcdcf73d/din-intresseanmalan-ar-mottagen
March 2, https://carpentries.topicbox.com/groups/local-middle-east/T68395a3e3040baaf/nova-registrace
February 25, https://carpentries.topicbox.com/groups/local-middle-east/T1c68df7c763514ad/ammenstuten-deutschland-inserat
February 19, https://carpentries.topicbox.com/groups/local-middle-east/T72a7b42588ec14ee/smp-climat-ru
February 19, https://carpentries.topicbox.com/groups/local-middle-east/Tc0157554a45d8507

Potential example of phishing messages:
February 4, https://carpentries.topicbox.com/groups/local-middle-east/Tebcb167c23f330e1/pending-delivery
January 20, https://carpentries.topicbox.com/groups/local-middle-east/Tc8516cdc6a5de79b

We should consider:
1. reviewing membership process
2. remove spammers from all mailing lists
3. delete spam messages

**Comment by acrall** [comment]
Thanks for bringing this to our attention, @annajiat. @maneesha, I went into TopicBox to see if I could change the settings to address these concerns, but I was unable to see who the admin was on the listserv. When I clicked "contact group admins," nothing happened. This is an issue that our team can address as part of the Community Development Program communications audit across all of our listservs.

**Comment by acrall** [comment]
@annajiat I have been made an admin on the mailing list and have made it where messages must be reviewed before they can be posted. This should get rid of new spam. I have also deleted the old spam messages from the inbox. I have added this as a task as we are reviewing our communications during the Community Development audit currently in progress. Thanks again for bringing this to our attention.
